version: '3.9'
services:
  mongo:
    image: mongo
    ports:
      - 9091:27017
    networks:
      - spring-network
  app:
    build: .
    environment:
      - spring.data.mongodb.host=mongo
    ports:
      - 9090:8080
    depends_on:
      - mongo
    networks:
      - spring-network
networks:
  spring-network: